CREATE TABLE [dbo].[person_activitie] (

	[type_d_identifiant_pp] varchar(8000) NULL, 
	[identifiant_pp] varchar(8000) NULL, 
	[identification_nationale_pp] varchar(8000) NULL, 
	[code_civilite_d_exercice] varchar(8000) NULL, 
	[libelle_civilite_d_exercice] varchar(8000) NULL, 
	[code_civilite] varchar(8000) NULL, 
	[libelle_civilite] varchar(8000) NULL, 
	[nom_d_exercice] varchar(8000) NULL, 
	[prenom_d_exercice] varchar(8000) NULL, 
	[code_profession] varchar(8000) NULL, 
	[libelle_profession] varchar(8000) NULL, 
	[code_categorie_professionnelle] varchar(8000) NULL, 
	[libelle_categorie_professionnelle] varchar(8000) NULL, 
	[code_type_savoir_faire] varchar(8000) NULL, 
	[libelle_type_savoir_faire] varchar(8000) NULL, 
	[code_savoir_faire] varchar(8000) NULL, 
	[libelle_savoir_faire] varchar(8000) NULL, 
	[code_mode_exercice] varchar(8000) NULL, 
	[libelle_mode_exercice] varchar(8000) NULL, 
	[numero_siret_site] varchar(8000) NULL, 
	[numero_siren_site] varchar(8000) NULL, 
	[numero_finess_site] varchar(8000) NULL, 
	[numero_finess_etablissement_juridique] varchar(8000) NULL, 
	[identifiant_technique_de_la_structure] varchar(8000) NULL, 
	[raison_sociale_site] varchar(8000) NULL, 
	[enseigne_commerciale_site] varchar(8000) NULL, 
	[complement_destinataire_coord._structure] varchar(8000) NULL, 
	[complement_point_geographique_coord._structure] varchar(8000) NULL, 
	[numero_voie_coord._structure] varchar(8000) NULL, 
	[indice_repetition_voie_coord._structure] varchar(8000) NULL, 
	[code_type_de_voie_coord._structure] varchar(8000) NULL, 
	[libelle_type_de_voie_coord._structure] varchar(8000) NULL, 
	[libelle_voie_coord._structure] varchar(8000) NULL, 
	[mention_distribution_coord._structure] varchar(8000) NULL, 
	[bureau_cedex_coord._structure] varchar(8000) NULL, 
	[code_postal_coord._structure] varchar(8000) NULL, 
	[code_commune_coord._structure] varchar(8000) NULL, 
	[libelle_commune_coord._structure] varchar(8000) NULL, 
	[code_pays_coord._structure] varchar(8000) NULL, 
	[libelle_pays_coord._structure] varchar(8000) NULL, 
	[telephone_coord._structure] varchar(8000) NULL, 
	[telephone_2_coord._structure] varchar(8000) NULL, 
	[telecopie_coord._structure] varchar(8000) NULL, 
	[adresse_e_mail_coord._structure] varchar(8000) NULL, 
	[code_departement_structure] varchar(8000) NULL, 
	[libelle_departement_structure] varchar(8000) NULL, 
	[ancien_identifiant_de_la_structure] varchar(8000) NULL, 
	[autorite_d_enregistrement] varchar(8000) NULL, 
	[code_secteur_d_activite] varchar(8000) NULL, 
	[libelle_secteur_d_activite] varchar(8000) NULL, 
	[code_section_tableau_pharmaciens] varchar(8000) NULL, 
	[libelle_section_tableau_pharmaciens] varchar(8000) NULL, 
	[code_role] varchar(8000) NULL, 
	[libelle_role] varchar(8000) NULL, 
	[code_genre_activite] varchar(8000) NULL, 
	[libelle_genre_activite] varchar(8000) NULL, 
	[_c56] varchar(8000) NULL
);


GO
ALTER TABLE [dbo].[person_activitie] ADD CONSTRAINT UQ_67736ee0_762a_41f9_82c8_f1e921dfab5d unique NONCLUSTERED ([numero_finess_site]);